// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: event_action.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "../tile/tile.capnp.h"
#include "../winds.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(bf2315493c1ef994);
CAPNP_DECLARE_SCHEMA(e627577d92ad63e5);
enum class ActionType_e627577d92ad63e5: uint16_t {
  DISCARD_TILE,
  CALL_RIICHI,
  CALL_KAN,
  CALL_PON,
  CALL_CHI,
  CALL_RON,
  CALL_TSUMO,
  DECLINE_CALL,
};
CAPNP_DECLARE_ENUM(ActionType, e627577d92ad63e5);

}  // namespace schemas
}  // namespace capnp


struct Action {
  Action() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::ActionType_e627577d92ad63e5 ActionType;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(bf2315493c1ef994, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Action::Reader {
public:
  typedef Action Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::Action::ActionType getType() const;

  inline  ::Wind getPlayerSeat() const;

  inline  ::Tile getTile() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Action::Builder {
public:
  typedef Action Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::Action::ActionType getType();
  inline void setType( ::Action::ActionType value);

  inline  ::Wind getPlayerSeat();
  inline void setPlayerSeat( ::Wind value);

  inline  ::Tile getTile();
  inline void setTile( ::Tile value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Action::Pipeline {
public:
  typedef Action Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::Action::ActionType Action::Reader::getType() const {
  return _reader.getDataField< ::Action::ActionType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::Action::ActionType Action::Builder::getType() {
  return _builder.getDataField< ::Action::ActionType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Action::Builder::setType( ::Action::ActionType value) {
  _builder.setDataField< ::Action::ActionType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::Wind Action::Reader::getPlayerSeat() const {
  return _reader.getDataField< ::Wind>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::Wind Action::Builder::getPlayerSeat() {
  return _builder.getDataField< ::Wind>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Action::Builder::setPlayerSeat( ::Wind value) {
  _builder.setDataField< ::Wind>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::Tile Action::Reader::getTile() const {
  return _reader.getDataField< ::Tile>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::Tile Action::Builder::getTile() {
  return _builder.getDataField< ::Tile>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Action::Builder::setTile( ::Tile value) {
  _builder.setDataField< ::Tile>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}


CAPNP_END_HEADER

