// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: tile.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(fee74effbff1f44f);
enum class Tile_fee74effbff1f44f: uint16_t {
  NONE,
  PIN_ONE,
  PIN_TWO,
  PIN_THREE,
  PIN_FOUR,
  PIN_FIVE,
  PIN_RED_FIVE,
  PIN_SIX,
  PIN_SEVEN,
  PIN_EIGHT,
  PIN_NINE,
  SOU_ONE,
  SOU_TWO,
  SOU_THREE,
  SOU_FOUR,
  SOU_FIVE,
  SOU_RED_FIVE,
  SOU_SIX,
  SOU_SEVEN,
  SOU_EIGHT,
  SOU_NINE,
  MAN_ONE,
  MAN_TWO,
  MAN_THREE,
  MAN_FOUR,
  MAN_FIVE,
  MAN_RED_FIVE,
  MAN_SIX,
  MAN_SEVEN,
  MAN_EIGHT,
  MAN_NINE,
  HONOR_EAST,
  HONOR_SOUTH,
  HONOR_WEST,
  HONOR_NORTH,
  HONOR_RED_DRAGON,
  HONOR_WHITE_DRAGON,
  HONOR_GREEN_DRAGON,
};
CAPNP_DECLARE_ENUM(Tile, fee74effbff1f44f);

}  // namespace schemas
}  // namespace capnp


typedef ::capnp::schemas::Tile_fee74effbff1f44f Tile;

// =======================================================================================

// =======================================================================================


CAPNP_END_HEADER

