// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: winds.capnp

#include "winds.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<33> b_9fc6869abdc189f0 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    240, 137, 193, 189, 154, 134, 198, 159,
     12,   0,   0,   0,   2,   0,   0,   0,
    121,  55,  98, 249,  22,  70, 100, 147,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 138,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0, 103,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    119, 105, 110, 100, 115,  46,  99,  97,
    112, 110, 112,  58,  87, 105, 110, 100,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     16,   0,   0,   0,   1,   0,   2,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      3,   0,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    101,  97, 115, 116,   0,   0,   0,   0,
    115, 111, 117, 116, 104,   0,   0,   0,
    119, 101, 115, 116,   0,   0,   0,   0,
    110, 111, 114, 116, 104,   0,   0,   0, }
};
::capnp::word const* const bp_9fc6869abdc189f0 = b_9fc6869abdc189f0.words;
#if !CAPNP_LITE
static const uint16_t m_9fc6869abdc189f0[] = {0, 3, 1, 2};
const ::capnp::_::RawSchema s_9fc6869abdc189f0 = {
  0x9fc6869abdc189f0, b_9fc6869abdc189f0.words, 33, nullptr, m_9fc6869abdc189f0,
  0, 4, nullptr, nullptr, nullptr, { &s_9fc6869abdc189f0, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
CAPNP_DEFINE_ENUM(Wind_9fc6869abdc189f0, 9fc6869abdc189f0);
}  // namespace schemas
}  // namespace capnp
