// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: player.capnp

#include "player.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<49> b_fc4b35e090c036c2 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    194,  54, 192, 144, 224,  53,  75, 252,
     20,   0,   0,   0,   1,   0,   2,   0,
    172,  72, 207, 155, 249,  53, 148, 246,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 218,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     99, 108, 105, 101, 110, 116,  47, 112,
    108,  97, 121, 101, 114,  46,  99,  97,
    112, 110, 112,  58,  80, 108,  97, 121,
    101, 114,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     49,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     44,   0,   0,   0,   3,   0,   1,   0,
     56,   0,   0,   0,   2,   0,   1,   0,
    112, 108,  97, 121, 101, 114,  73, 100,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    115,  99, 111, 114, 101,   0,   0,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_fc4b35e090c036c2 = b_fc4b35e090c036c2.words;
#if !CAPNP_LITE
static const uint16_t m_fc4b35e090c036c2[] = {0, 1};
static const uint16_t i_fc4b35e090c036c2[] = {0, 1};
const ::capnp::_::RawSchema s_fc4b35e090c036c2 = {
  0xfc4b35e090c036c2, b_fc4b35e090c036c2.words, 49, nullptr, m_fc4b35e090c036c2,
  0, 2, i_fc4b35e090c036c2, nullptr, nullptr, { &s_fc4b35e090c036c2, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// Player
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t Player::_capnpPrivate::dataWordSize;
constexpr uint16_t Player::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind Player::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Player::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE



