// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: player_left_lobby.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "queue_player.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(bf6b154e1030d2df);
enum class LeaveReason_bf6b154e1030d2df: uint16_t {
  DISCONNECT,
  USER_QUIT,
  TIMEOUT,
  SYSTEM_ERROR,
};
CAPNP_DECLARE_ENUM(LeaveReason, bf6b154e1030d2df);
CAPNP_DECLARE_SCHEMA(f3af1d2c924f184e);

}  // namespace schemas
}  // namespace capnp


typedef ::capnp::schemas::LeaveReason_bf6b154e1030d2df LeaveReason;

struct PlayerLeftLobby {
  PlayerLeftLobby() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f3af1d2c924f184e, 2, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class PlayerLeftLobby::Reader {
public:
  typedef PlayerLeftLobby Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasLobbyId() const;
  inline  ::capnp::Data::Reader getLobbyId() const;

  inline bool hasPlayerId() const;
  inline  ::capnp::Text::Reader getPlayerId() const;

  inline  ::LeaveReason getReason() const;

  inline bool hasRemainingPlayers() const;
  inline  ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Reader getRemainingPlayers() const;

  inline  ::uint64_t getTimestampMs() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PlayerLeftLobby::Builder {
public:
  typedef PlayerLeftLobby Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasLobbyId();
  inline  ::capnp::Data::Builder getLobbyId();
  inline void setLobbyId( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initLobbyId(unsigned int size);
  inline void adoptLobbyId(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownLobbyId();

  inline bool hasPlayerId();
  inline  ::capnp::Text::Builder getPlayerId();
  inline void setPlayerId( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initPlayerId(unsigned int size);
  inline void adoptPlayerId(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownPlayerId();

  inline  ::LeaveReason getReason();
  inline void setReason( ::LeaveReason value);

  inline bool hasRemainingPlayers();
  inline  ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Builder getRemainingPlayers();
  inline void setRemainingPlayers( ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Builder initRemainingPlayers(unsigned int size);
  inline void adoptRemainingPlayers(::capnp::Orphan< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>> disownRemainingPlayers();

  inline  ::uint64_t getTimestampMs();
  inline void setTimestampMs( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PlayerLeftLobby::Pipeline {
public:
  typedef PlayerLeftLobby Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool PlayerLeftLobby::Reader::hasLobbyId() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PlayerLeftLobby::Builder::hasLobbyId() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader PlayerLeftLobby::Reader::getLobbyId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder PlayerLeftLobby::Builder::getLobbyId() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PlayerLeftLobby::Builder::setLobbyId( ::capnp::Data::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder PlayerLeftLobby::Builder::initLobbyId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void PlayerLeftLobby::Builder::adoptLobbyId(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> PlayerLeftLobby::Builder::disownLobbyId() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool PlayerLeftLobby::Reader::hasPlayerId() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool PlayerLeftLobby::Builder::hasPlayerId() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader PlayerLeftLobby::Reader::getPlayerId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder PlayerLeftLobby::Builder::getPlayerId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void PlayerLeftLobby::Builder::setPlayerId( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder PlayerLeftLobby::Builder::initPlayerId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void PlayerLeftLobby::Builder::adoptPlayerId(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> PlayerLeftLobby::Builder::disownPlayerId() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline  ::LeaveReason PlayerLeftLobby::Reader::getReason() const {
  return _reader.getDataField< ::LeaveReason>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::LeaveReason PlayerLeftLobby::Builder::getReason() {
  return _builder.getDataField< ::LeaveReason>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void PlayerLeftLobby::Builder::setReason( ::LeaveReason value) {
  _builder.setDataField< ::LeaveReason>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool PlayerLeftLobby::Reader::hasRemainingPlayers() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool PlayerLeftLobby::Builder::hasRemainingPlayers() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Reader PlayerLeftLobby::Reader::getRemainingPlayers() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Builder PlayerLeftLobby::Builder::getRemainingPlayers() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void PlayerLeftLobby::Builder::setRemainingPlayers( ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>::Builder PlayerLeftLobby::Builder::initRemainingPlayers(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void PlayerLeftLobby::Builder::adoptRemainingPlayers(
    ::capnp::Orphan< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>> PlayerLeftLobby::Builder::disownRemainingPlayers() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::QueuePlayer,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline  ::uint64_t PlayerLeftLobby::Reader::getTimestampMs() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t PlayerLeftLobby::Builder::getTimestampMs() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void PlayerLeftLobby::Builder::setTimestampMs( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}


CAPNP_END_HEADER

