// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: winds.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(9fc6869abdc189f0);
enum class Wind_9fc6869abdc189f0: uint16_t {
  EAST,
  SOUTH,
  WEST,
  NORTH,
};
CAPNP_DECLARE_ENUM(Wind, 9fc6869abdc189f0);

}  // namespace schemas
}  // namespace capnp


typedef ::capnp::schemas::Wind_9fc6869abdc189f0 Wind;

// =======================================================================================

// =======================================================================================


CAPNP_END_HEADER

